
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: LEGACYHTML5
server:
  port: 80

wx:
  appid:
  secret:
  grant_type: authorization_code
  request_url: https://api.weixin.qq.com/sns/oauth2/access_token?
  userinfo_url: https://api.weixin.qq.com/sns/userinfo?
