spring:
  thymeleaf:
    content-type: text/html
    mode: LEGACYHTML5
    cache: false
server:
  port: 80

wx:
  appid: wx9c2707e2093dee43
  secret: 13c00c8d2397f82c54b94452d36dc4b7
  grant_type: authorization_code
  request_url: https://api.weixin.qq.com/sns/oauth2/access_token?